version: "3"
services:
  r_datascience_debug:
    #image: r_datascience
    image: rocker/verse:3.6.1
    # restart: unless-stopped
    ports:
      - "8787:8787" #rstudio
    volumes:
      - ./volume:/home/rstudio/.rstudio/monitored/user-settings/
    environment:
      - DISPLAY=$DISPLAY
      - PASSWORD=password
      - ROOT=TRUE
    tty: true
