version: '3.8'
services:
  pdatascience:
    image: pdsc_jpylab_gpu_run:latest
    container_name: pdsc_jpylab_gpu_run
    # restart: unless-stopped
    ports:
      - "127.0.0.1:6006:6006" # tensorflow
      - "127.0.0.1:8888:8888" # jupyterlab
    volumes:
      - /mount/this/folder:/home/user/development
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu

# vgl. https://github.com/docker/compose/issues/6691

# docker run --gpus=all \
#   -v /mount/this/folder:/home/user/development \
#   -u $(id -u):$(id -g) \
#   -p 127.0.0.1:6006:6006 \
#   -p 127.0.0.1:8888:8888 \
#   -it \
#   pdsc_jpylab_gpu:latest
