version: '3'
services:
  python_ds_re:
    container_name: pdatascience_re
    image: p_datascience_re:latest
    # restart: unless-stopped
    # ports:
    # - "50022:22"
    volumes:
    - ./volume:/home/user/volume
    build:
      context: .
    networks:
      - pdatascience_re
    tty: true

networks:
    pdatascience_re:
